"""add new table movie

Revision ID: 3efec48c68d0
Revises: 2ae83eeaee35
Create Date: 2014-02-25 14:30:31.198750

"""

# revision identifiers, used by Alembic.
revision = '3efec48c68d0'
down_revision = '2ae83eeaee35'

from alembic import op
from sqlalchemy.dialects import mysql

import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    op.drop_table('movies')
    ### end Alembic commands ###
